export const PENDING_SALE_STATUS = {
  PENDING: "pending",
  CONFIRMED: "confirmed",
  REJECTED: "rejected",
};

export const PENDING_SALE_STATUSES = [
  PENDING_SALE_STATUS.PENDING,
  PENDING_SALE_STATUS.CONFIRMED,
  PENDING_SALE_STATUS.REJECTED,
];
