const NUMBER_TRAFFIC_SOURCES = Array.from(
  { length: 15 },
  (_, index) => String(index + 1)
);

const TARGET_TRAFFIC_SOURCES = Array.from(
  { length: 20 },
  (_, index) => `Таргет ${index + 1}`
);

/** @deprecated Range entries replaced by individual items */
export const OBSOLETE_TRAFFIC_SOURCE_NAMES = [
  "1-15",
  "Таргет 1-20",
];

export const INITIAL_TRAFFIC_SOURCE_NAMES = [
  ...NUMBER_TRAFFIC_SOURCES,
  ...TARGET_TRAFFIC_SOURCES,
  "Кеноби",
  "Swerok",
  "Соболь",
  "Векши",
  "Гисми",
  "Квертин",
  "Никита 2504",
  "Kenobi 2",
  "Swerok 2",
  "FLV",
  "FLV 2",
  "Ожидание",
  "KULT",
  "Tekker",
  "УБИВАЮ BPM",
  "Бебраниум",
  "Cars Japan",
  "Bono Machan",
  "Куперштейн",
  "Splice",
  "AbaDead",
  "Ktowho",
  "Kipers",
  "Рамен",
  "Рамен 2",
  "Bono Machan 2",
  "Кеноби 3",
  "Рамен 3",
  "Данквист",
  "Дубак",
  "Токсик",
  "Кроль краб",
  "Вонвонк",
  "Re:2D",
  "Канал Нела",
  "Даниэль",
  "Вафлекинг",
  "Аробки",
  "Скума",
  "Кулек",
  "Арнкратос",
  "Метхольчик",
  "Айдо",
  "Решат",
  "Реникс",
  "Махех",
  "Кселт",
  "Качанов",
  "Шапка",
  "Януарий",
  "Паник2D",
  "Марчиз",
  "Комрад",
  "Алластер",
  "Райдзин",
  "Кодлок",
  "Тарков17",
  "Качанов 2",
  "Пакет",
  "СониК",
  "Гантрапа",
  "Сачельник",
  "Денис Канал",
  "Двушка",
  "Топляк",
  "Амазозла",
  "Шкед",
  "Глутон",
  "Денис канал 2",
  "Сюс",
  "Клио",
  "Кель",
  "Шапка 2",
  "Слэш",
  "Ючия",
  "Анимиллион",
  "Метхольчик 2",
  "BVS",
  "Кинокос",
  "Мейтич",
  "Марчиз 2",
  "Кекус",
  "Шапка 3",
  "Бубр",
  "Шапка 4",
  "База",
];
